import { Inter } from '@next/font/google';
import { GetStaticProps } from 'next';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
import { ReactElement } from 'react';

import Header from '@/components/Header';
import Layout from '@/components/Layout';
import Stock from '@/components/Stock/Stock';
import { DEFAULT_LOCALE } from '@/utils/constants';
import { NextPageWithLayout } from '@/utils/types';

const inter = Inter({ subsets: ['latin'] });

const Home: NextPageWithLayout = () => {
  return (
    <>
      {/* <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head> */}

      <Header />

      <Stock />
    </>
  );
};

Home.getLayout = function getLayout(page: ReactElement) {
  return <Layout>{page}</Layout>;
};

export const getStaticProps: GetStaticProps = async ({ locale = DEFAULT_LOCALE }) => {
  return {
    props: {
      ...(await serverSideTranslations(locale, ['seo'])),
    },
  };
};

export default Home;
